/***************************************************************************/
/*                                                                         */
/*  JMFFilter.m                                                            */
/*  Copyright (c) 2014 Simarks. All rights reserved.                       */
/*                                                                         */
/*  Description: JMFCameraIOS                                              */
/*               U-Tad - Práctica iOS Avanzado                             */
/*               CoreData Filter Entity Class implementation file          */
/*                                                                         */
/*       Author: Jorge Marcos Fernandez                                    */
/*         NOTE: Generated by mogenerator                                  */
/*                                                                         */
/***************************************************************************/
#import "JMFFilter.h"

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  JMFFilter Class Interface                                              */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
@interface JMFFilter ()

// Private interface goes here.

@end

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*  JMFFilter Class implementation                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
@implementation JMFFilter


#pragma mark - Key Value Observing Methods
/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*  Key Value Observing Methods                                            */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  observableKeys                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
+ (NSArray*)observableKeys
{
    return @[JMFNamedEntityAttributes.name, JMFNamedEntityAttributes.creationDate, JMFFilterRelationships.photo];
}

#pragma mark - Initialization Methods
/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*  Initialization Methods                                                 */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  faceWithName:feature:inContext:                                        */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
+ (instancetype)filterWithName:(NSString*)name photo:(JMFPhoto*)photo inContext:(NSManagedObjectContext*)context
{
    JMFFilter* filter = [JMFFilter insertInManagedObjectContext:context];
    
    filter.photo = photo;
    filter.name = name;
    filter.creationDate = filter.modificationDate = [NSDate date];
    
    return filter;
}

#pragma mark - Instance Methods
/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*  Instance Methods                                                       */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  isActive                                                               */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
- (BOOL)isActive
{
    return( self.activeValue );
}

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  isValidFilter                                                          */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
- (BOOL)isValidFilter
{
    return( ![self.name isEqualToString:@"CIFilterNone"] );
}

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  activeToString                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
- (NSString*)activeToString
{
    NSString* localizedString = ( self.activeValue ) ? @"IDS_YES" : @"IDS_NO";
    return NSLocalizedString( localizedString, nil );
}

@end
