/***************************************************************************/
/*                                                                         */
/*  JMFFace.m                                                              */
/*  Copyright (c) 2014 Simarks. All rights reserved.                       */
/*                                                                         */
/*  Description: JMFCameraIOS                                              */
/*               U-Tad - Práctica iOS Avanzado                             */
/*               CoreData Face Entity Class implementation file            */
/*                                                                         */
/*       Author: Jorge Marcos Fernandez                                    */
/*         NOTE: Generated by mogenerator                                  */
/*                                                                         */
/***************************************************************************/
#import "JMFFace.h"

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  JMFFace Class Interface                                                */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
@interface JMFFace ()

// Private interface goes here.

@end

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*  JMFFace Class implementation                                           */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
@implementation JMFFace

// Custom logic goes here.

@end
