/***************************************************************************/
/*                                                                         */
/*  JMFFilter.h                                                            */
/*  Copyright (c) 2014 Simarks. All rights reserved.                       */
/*                                                                         */
/*  Description: JMFCameraIOS                                              */
/*               U-Tad - Práctica iOS Avanzado                             */
/*               CoreData Filter Entity Class definition file              */
/*                                                                         */
/*       Author: Jorge Marcos Fernandez                                    */
/*         NOTE: Generated by mogenerator                                  */
/*                                                                         */
/***************************************************************************/
#import "_JMFFilter.h"
#import "JMFFilterProperty.h"

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  Defines                                                                */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
#define IDS_FILTER_NONE                             @"CIFilterNone"

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*  FilterProperties Singleton Interface definition                        */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
@interface FilterProperties : NSObject

+ (NSArray*)filterProperties;

@end

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*  JMFFilter Class Interface                                              */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
@interface JMFFilter : _JMFFilter

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  Properties                                                             */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
@property (nonatomic,strong) NSManagedObjectContext*    context;

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  Initialization Methods                                                 */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
+ (instancetype)filterWithName:(NSString*)name photo:(JMFPhoto*)photo inContext:(NSManagedObjectContext*)context;

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  Instance Methods                                                       */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
- (void)setNewName:(NSString*)newName;
- (void)createProperties;
- (void)deleteProperties;
- (NSFetchedResultsController*)propertiesResultsController;
- (BOOL)isActive;
- (BOOL)isValidFilter;
- (NSString*)activeToString;

@end

