/***************************************************************************/
/*                                                                         */
/*  JMFNamedEntity.m                                                       */
/*  Copyright (c) 2014 Simarks. All rights reserved.                       */
/*                                                                         */
/*  Description: JMFCameraIOS                                              */
/*               U-Tad - Práctica iOS Avanzado                             */
/*               CoreData NamedEntity Entity Class implementation file     */
/*                                                                         */
/*       Author: Jorge Marcos Fernandez                                    */
/*         NOTE: Generated by mogenerator                                  */
/*                                                                         */
/***************************************************************************/
#import "JMFNamedEntity.h"

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  JMFNamedEntity Class Interface                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
@interface JMFNamedEntity ()

// Private interface goes here.

@end

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*  JMFNamedEntity Class implementation                                    */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
@implementation JMFNamedEntity

@synthesize creationDate     = _creationDate;
@synthesize modificationDate = _modificationDate;

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  Custom Creation Date setter                                            */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
- (void)setCreationDate:(NSDate*)date
{
    _creationDate = date;
    _modificationDate = date;
}

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  Custom Modification Date setter                                        */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
- (void)setModificationDate:(NSDate*)date
{
    _modificationDate = date;
}

@end