/***************************************************************************/
/*                                                                         */
/*  JMFPhoto.h                                                             */
/*  Copyright (c) 2014 Simarks. All rights reserved.                       */
/*                                                                         */
/*  Description: JMFCameraIOS                                              */
/*               U-Tad - Práctica iOS Avanzado                             */
/*               CoreData Photo Entity Class definition file               */
/*                                                                         */
/*       Author: Jorge Marcos Fernandez                                    */
/*         NOTE: Generated by mogenerator                                  */
/*                                                                         */
/***************************************************************************/
#import "_JMFPhoto.h"

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  Enums                                                                  */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
typedef NS_ENUM( NSInteger, JMFPhotoSource )
{
    JMFPhotoSourceUnknown    =  0,
    JMFPhotoSourceCamera     =  1,
    JMFPhotoSourceFlickr     =  2,
    JMFPhotoSourceFeacebook  =  3,
    JMFPhotoSourceInstagram  =  4,
    JMFPhotoSourceTwitter    =  5,
    JMFPhotoSourceOther      = -1
};

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*  JMFPhoto Class Interface                                               */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
@interface JMFPhoto : _JMFPhoto

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  Initialization Methods                                                 */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
- (id)initWithImage:(UIImage*)image source:(JMFPhotoSource)source andThumbnail:(UIImage*)thumbnail;

/***************************************************************************/
/*                                                                         */
/*                                                                         */
/*  Instance Methods                                                       */
/*                                                                         */
/*                                                                         */
/***************************************************************************/
- (void)saveImageFile:(UIImage*)image withTumbnail:(UIImage*)thumbnail;
- (void)setMetadataFromImage:(UIImage*)image;
- (void)setLocationLongitude:(NSNumber*)longitude latitude:(NSNumber*)latitude altitude:(NSNumber*)altitude geoLocation:(NSString*)geoLocation;

@end

